### ISSUE TITLE
UpdateChecker causes crash

### ISSUE THREAD

**Issue by maxhenkes** [Brian-Wuest/MC-Repurpose#3] opened 2016-08-20 22:43 UTC
Since there is no config to disable the update checker, I've had to remove your mod because it's crashing our client's on loading. It worked fine earlier today.

Crash:

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 7 column 5
    at com.google.gson.Gson.fromJson(Gson.java:818)
    at com.google.gson.Gson.fromJson(Gson.java:741)
    at com.wuest.utilities.UpdateChecker.getRepositoryVersion(UpdateChecker.java:55)
    at com.wuest.utilities.UpdateChecker.checkVersion(UpdateChecker.java:21)
    at com.wuest.utilities.Proxy.CommonProxy.preInit(CommonProxy.java:56)
    at com.wuest.utilities.Proxy.ClientProxy.preInit(ClientProxy.java:41)
    at com.wuest.utilities.WuestUtilities.preInit(WuestUtilities.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:255)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 7 column 5
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
    at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:166)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.Gson.fromJson(Gson.java:803)
    ... 42 more

**Comment by brisingraerowing** [comment] 2016-08-21 03:31
Same issue here. I'm going to revert to the previous working version for now.

**Comment by brisingraerowing** [comment] 2016-08-21 03:39
This issue is caused by an unterminated string.

https://github.com/Brian-Wuest/MC-WuestUtilities/blob/MC-1.10.2/src/main/resources/mcmod.info#L6

@Brian-Wuest

**Comment by maxhenkes** [comment] 2016-08-21 03:41
Ah a typo :P Bad luck ^^ But there should be a config option. He basically broke my entire modpack for a few hours. Id rather manually update mods than this.

**Comment by Brian-Wuest** [comment] 2016-08-21 05:22
Ouch..sorry about that everyone. I will update in the morning.

Edit: I am fixing this now.

**Comment by Brian-Wuest** [comment] 2016-08-21 05:49
I have fixed the mcmod.info file so the published version will no longer crash. You will still get an error about the localized mcmod.info file having bad json but it won't crash the game (I tested that locally).

I will be releasing 1.10.2.5 shortly to correct the local json file.

**Comment by maxhenkes** [comment] 2016-08-21 05:49
Awesome! That way I can re-add the mod to my pack tomorrow :) Thanks for the quick fix!

**Comment by Brian-Wuest** [comment] 2016-08-21 05:55
No problem, sorry that this happened. Should have done more testing!

Later this week I will add a configuration option to disable the update checker.

A separate issue will be created to track that progress. A similar one will be created for Prefab as well.

Closing this issue.

**Closed as completed by Brian-Wuest** 2016-08-21 05:55 UTC
Labels: bug

**Comment by Brian-Wuest** [comment] 2016-08-21 06:06
Update checker configuration option is being tracked with #5. I will most likely start looking at this tomorrow.

Also, 1.10.2.5 is available.

**Comment by Denubis** [comment] 2016-08-21 22:35
Thanks much for acting on this!
